# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('episode_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('hero_image', models.ImageField(upload_to='images')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
